collections:
  authors:
    output: true
  hamsters:
    output: true

defaults:
  - scope:
      path: ''
      type: 'authors'
    values:
      layout: 'author'
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
  - scope:
      path: ''
    values:
      layout: 'default'

exclude: [
  README.md,
  goals.md,
  package-lock.json,
  package.json
]

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  load_paths:
    - _sass
    - node_modules
